### ISSUE TITLE
`Preset.extract()` avec un dotdirectory

### ISSUE THREAD

**Issue by rubuano** [mgkprod/presets#1]
La copie du répertoire `templates/config/.vscode` ne fonctionne pas.

https://github.com/mgkprod/presets/blob/1fc656b8b3989ed3f738d4a4d6a9668eea4a987d/config/preset.js#L10

Workaround :
https://github.com/mgkprod/presets/blob/1fc656b8b3989ed3f738d4a4d6a9668eea4a987d/config/preset.js#L12-L17

**Comment by innocenzi** [comment]
Meilleur workaround : 

```ts
Preset.extract('config/_vscode').to('.vscode');
```

Je vais sûrement ajouter une option pour autoriser les dotfiles, mais c'est un sujet complexe (y'a plein de cas particuliers)

**Comment by innocenzi** [comment]
La dernière version devrait fonctionner si tu utilises `withDots` :

```js
Preset.extract().withDots(true);
```

**Comment by rubuano** [comment]
Top, ça fonctionne !

Merci :p
