### ISSUE TITLE
`Preset.edit().addAfter()` ne fonctionne pas comme attendu

### ISSUE THREAD

**Issue by rubuano** [mgkprod/presets#2]
Le contenu n'est pas trouvé avec une recherche par regex

https://github.com/mgkprod/presets/blob/0930ac7a5423bc6ae3868080b0707ab8ec47b834/config/preset.js#L33-L47

Mais également, lors d'une recherche par string

https://github.com/mgkprod/presets/blob/0930ac7a5423bc6ae3868080b0707ab8ec47b834/config/preset.js#L23-L31

Impacts :

https://github.com/mgkprod/presets/blob/main/config/preset.js#L24
https://github.com/mgkprod/presets/blob/main/config/preset.js#L24
https://github.com/mgkprod/presets/blob/main/version/preset.js#L6
https://github.com/mgkprod/presets/blob/main/version/preset.js#L16

**Comment by innocenzi** [comment]
C'est parce que cette action utilise `match`, donc l'argument passé doit être un string ou une regexp, et si c'est un string ça doit contenir la regexp. C'est confus donc je vais sûrement améliorer ça, mais en attendant tu peux juste utiliser une regexp normale : 

```ts
.addAfter(/use Illuminate\\Support\\ServiceProvider;/, [])
```

**Comment by rubuano** [comment]
J'ai ici cette utilisation avec [cette regex](https://regex101.com/r/SytG96/1) :

```javascript
Preset.edit('app/Providers/AppServiceProvider.php')
    .addAfter(/public function register\(\)(\s*){/m, [
		''
    ])
```

pour détecter à la fois :

```php
public function register()
    {
```

et :

```php
public function register(){
```

Le fichier n'est pas modifié. Est-ce que le match fonctionne sur du multi-line ?

En revanche, celle-ci fonctionne :

```javascript
.addAfter(/use Illuminate\\Support\\ServiceProvider;/, [])
```

**Comment by innocenzi** [comment]
Non, `match` fonctionne que sur une seule ligne, parce que le fichier est `split` par retour à la ligne pour supporter `addBefore`

C'est pour ce cas de figure qu'il y a `skipLines`, pour pouvoir ajouter du contenu dans le corps d'une méthode après l'avoir match

**Comment by rubuano** [comment]
> Non, `match` fonctionne que sur une seule ligne, parce que le fichier est `split` par retour à la ligne pour supporter `addBefore`
> 
> C'est pour ce cas de figure qu'il y a `skipLines`, pour pouvoir ajouter du contenu dans le corps d'une méthode après l'avoir match

Dommage mais ok!
