### ISSUE TITLE
`Preset.apply()` relatif

### ISSUE THREAD

**Issue by rubuano** [mgkprod/presets#3]
Je ne sais pas si c'est une idée d'amélioration ou un bug, mais le code suivant ne fonctionne pas. Et c'est bien dommage 😭 

https://github.com/mgkprod/presets/blob/0930ac7a5423bc6ae3868080b0707ab8ec47b834/new/preset.js#L19-L22

**Comment by innocenzi** [comment]
Tu peux le faire de deux manières : 
- En appliquant le preset en passant son resolvable (ici `mgkprod/presets`) avec des arguments
- En utilisant `preset.targetDirectory`

Je te conseille le second, qui est plus efficace (il re-télécharge pas le dépôt) : 

```js
Preset.apply(({ targetDirectory }) => `${targetDirectory}/config`);
```

On peut pas vraiment le faire de manière relative parce que ce que tu passes à `apply` est un resolvable qui est l'équivalent de ce que tu passes en ligne de commande, donc ça doit être quelque chose que les resolvers comprennent.

**Comment by rubuano** [comment]
`preset.targetDirectory` renvoyant le dossier dans lequel est appliqué le preset, j'ai utilisé `preset.presetDirectory`.

Cependant, impossible de faire fonctionner l'apply de manière relative.

Cas 1:

![image](https://user-images.githubusercontent.com/33329579/102005238-964b6e00-3d17-11eb-91ad-aac7c4e82384.png)
![image](https://user-images.githubusercontent.com/33329579/102005243-a06d6c80-3d17-11eb-895c-366dbb6becc6.png)

Cas 2:

![image](https://user-images.githubusercontent.com/33329579/102005217-6ac88380-3d17-11eb-8a1d-4f00bb08bb70.png)
![image](https://user-images.githubusercontent.com/33329579/102005224-76b44580-3d17-11eb-9ffb-7ecf0c00724b.png)
(c'est joli mais ça ne s'arrête jamais)

Au passage, cas 3, en passant par le resolvable: 

![image](https://user-images.githubusercontent.com/33329579/102005275-e1658100-3d17-11eb-8aa2-84d0a03e1034.png)
![image](https://user-images.githubusercontent.com/33329579/102005264-cd218400-3d17-11eb-8b6b-138eff276af0.png)

En fait je me suis rendu compte que le clone ne fonctionnait pas du tout chez moi:
![image](https://user-images.githubusercontent.com/33329579/102005291-fd692280-3d17-11eb-808a-4df39f32c25c.png)

**Comment by innocenzi** [comment]
La récursion devrait être corrigée avec https://github.com/use-preset/cli/releases/tag/v0.2.9. Tu peux utiliser un preset relatif comme tu as fait, en utilisant le resolvable (attention, ça va cloner plusieurs fois) ou en utilisant `path` : 

```ts
import path from 'path';

Preset.apply(({ presetDirectory }) => path.join(presetDirectory, '..', 'config'));
```

Si tu utilises le resolvable, utilise `with('--path=config')` plutôt que `with('--path config')`
