### ISSUE TITLE
Opérations filesystem

### ISSUE THREAD

**Issue by rubuano** [mgkprod/presets#5]
J'ai eu besoin d'appeler plusieurs fois des opérations de fichiers: `mv`, `cp`, `touch`

Il serait peut être judicieux d'en décliner une action !

L'intérêt serait double :

* Abstraction des commandes réalisées en `execute`
* Compatibilité cross-OS (actuellement c'est Win only)

**Comment by innocenzi** [comment]
Pour `touch` tu ferais mieux d'utiliser les templates, mais les deux autres sont des actions auxquelles j'ai déjà pensé et que je compte implémenter dans le futur, mais que je n'ai pas encore écrit parce que je ne les utilise pas encore moi-même ^^

**Comment by rubuano** [comment]
Ok pour ça
