### ISSUE TITLE
`Preset.edit()`: Créer le fichier si il n'existe pas

### ISSUE THREAD

**Issue by rubuano** [mgkprod/presets#6]
J'ai été surpris de voir que ce n'était pas le cas !

Impacts :

https://github.com/mgkprod/presets/blob/main/config/preset.js#L14
https://github.com/mgkprod/presets/blob/main/config/preset.js#L90
https://github.com/mgkprod/presets/blob/main/version/preset.js#L29

**Comment by innocenzi** [comment]
Si tu veux créer un fichier, tu devrais plutôt le mettre dans les `templates` (tu peux utiliser la stratégie `skip` pour ne pas le remplacer s'il existe). 

Ton preset ressemble plus à du scaffolding (ce pour quoi des outils comme SAO/Yeoman sont faits : https://usepreset.dev/docs/basics/alternatives/), et même si Preset peut faire ça, les actions sont plutôt pensées autour de l'édition de fichiers existants
