### ISSUE TITLE
`content` ?

### ISSUE THREAD

**Issue by rubuano** [mgkprod/presets#7]
Tu disais :

> les actions sont plutôt pensées autour de l'édition de fichiers existants

C'est donc ce que je me suis appliqué à faire dans mon preset VITL (https://github.com/mgkprod/presets/tree/main/vitl)

Cependant, impossible de faire fonctionner correctement mon `content.replace` ici :

https://github.com/mgkprod/presets/blob/f8e41c03d80a9b1cdd330a1f273188d3c99a6935/vitl/preset.js#L38-L53

le `content` que tu fournis, c'est le string directement ou un objet Preset ?

**Comment by innocenzi** [comment]
`content` n'est pas une référence, il faut que la fonction le retourne

Si tu enlèves les `{}` le `return` est implicite

**Comment by rubuano** [comment]
Désolé! Mauvaise connaissance du langage!
